In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('bodyfat.csv')
df=df.head(10)
df

,Unnamed: 0,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist,BodyCat
0,1,1.0708,12.3,23.0,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1,FIT
1,2,1.0853,6.1,22.0,173.25,NaN,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2,FIT
2,3,1.0414,25.3,22.0,154.00,66.25,34.0,95.8,87.9,99.2,0.0,38.9,24.0,28.8,25.2,16.6,OBESE
3,4,1.0751,NaN,26.0,NaN,NaN,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2,FIT
4,5,1.0340,28.7,24.0,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7,OBESE
5,6,1.0502,20.9,NaN,210.25,74.75,39.0,104.5,94.4,107.8,66.0,42.0,25.6,35.7,30.6,18.8,NORMAL
6,7,1.0549,19.2,26.0,NaN,69.75,36.4,105.1,90.7,100.3,58.4,38.3,22.9,NaN,27.8,17.7,NORMAL
7,8,1.0704,12.4,25.0,176.00,72.50,37.8,99.6,88.5,97.1,60.0,39.4,23.2,30.5,29.0,18.8,FIT
8,9,1.0900,4.1,25.0,191.00,74.00,38.1,100.9,82.5,99.9,62.9,38.3,23.8,35.9,31.1,18.2,FIT
9,10,1.0722,11.7,23.0,198.25,73.50,42.1,99.6,88.6,104.1,63.1,41.7,25.0,35.6,30.0,19.2,FIT

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   Density     10 non-null     float64
 2   BodyFat     9 non-null      float64
 3   Age         9 non-null      float64
 4   Weight      8 non-null      float64
 5   Height      8 non-null      float64
 6   Neck        10 non-null     float64
 7   Chest       10 non-null     float64
 8   Abdomen     10 non-null     float64
 9   Hip         10 non-null     float64
 10  Thigh       10 non-null     float64
 11  Knee        10 non-null     float64
 12  Ankle       10 non-null     float64
 13  Biceps      9 non-null      float64
 14  Forearm     10 non-null     float64
 15  Wrist       10 non-null     float64
 16  BodyCat     10 non-null     object
dtypes: float64(15), int64(1), object(1)
memory usage: 1.5+ KB
None

In [7]:
print(df.describe())

       Unnamed: 0    Density    BodyFat        Age      Weight     Height  \
count    10.00000  10.000000   9.000000   9.000000    8.000000   8.000000
mean      5.50000   1.064430  15.633333  24.000000  180.156250  71.218750
std       3.02765   0.018528   8.408181   1.581139   19.955727   3.068962
min       1.00000   1.034000   4.100000  22.000000  154.000000  66.250000
25%       3.25000   1.051375  11.700000  23.000000  168.500000  69.250000
50%       5.50000   1.070600  12.400000  24.000000  180.125000  71.875000
75%       7.75000   1.074375  20.900000  25.000000  192.812500  73.625000
max      10.00000   1.090000  28.700000  26.000000  210.250000  74.750000

            Neck       Chest     Abdomen         Hip      Thigh       Knee  \
count  10.000000   10.000000   10.000000   10.000000  10.000000  10.000000
mean   37.390000   99.130000   88.720000  100.470000  55.140000  39.270000
std     2.345421    4.170811    5.305511    3.675459  19.531524   1.989444
min    34.000000   93.100000   82.500000   94.500000   0.000000  37.300000
25%    36.250000   96.175000   85.500000   98.825000  58.775000  37.550000
50%    37.600000   99.600000   88.200000  100.100000  60.050000  38.600000
75%    38.400000  101.575000   90.175000  101.725000  63.050000  41.125000
max    42.100000  105.100000  100.000000  107.800000  66.000000  42.200000

           Ankle     Biceps    Forearm      Wrist
count  10.000000   9.000000  10.000000  10.000000
mean   23.660000  32.622222  28.710000  18.050000
std     1.080329   2.581559   1.745757   0.800347
min    21.900000  28.800000  25.200000  16.600000
25%    22.975000  30.500000  27.725000  17.700000
50%    23.600000  32.200000  28.950000  18.200000
75%    24.000000  35.600000  29.850000  18.650000
max    25.600000  35.900000  31.100000  19.200000

In [8]:
df.loc[4]

Unnamed: 0         5
Density        1.034
BodyFat         28.7
Age             24.0
Weight        184.25
Height         71.25
Neck            34.4
Chest           97.3
Abdomen        100.0
Hip            101.9
Thigh           63.2
Knee            42.2
Ankle           24.0
Biceps          32.2
Forearm         27.7
Wrist           17.7
BodyCat        OBESE
Name: 4, dtype: object

In [11]:
df.iloc[4]

Unnamed: 0         5
Density        1.034
BodyFat         28.7
Age             24.0
Weight        184.25
Height         71.25
Neck            34.4
Chest           97.3
Abdomen        100.0
Hip            101.9
Thigh           63.2
Knee            42.2
Ankle           24.0
Biceps          32.2
Forearm         27.7
Wrist           17.7
BodyCat        OBESE
Name: 4, dtype: object

In [9]:
df.isnull().any()

Unnamed: 0    False
Density       False
BodyFat        True
Age            True
Weight         True
Height         True
Neck          False
Chest         False
Abdomen       False
Hip           False
Thigh         False
Knee          False
Ankle         False
Biceps         True
Forearm       False
Wrist         False
BodyCat       False
dtype: bool

In [10]:
df.isnull().sum()

Unnamed: 0    0
Density       0
BodyFat       1
Age           1
Weight        2
Height        2
Neck          0
Chest         0
Abdomen       0
Hip           0
Thigh         0
Knee          0
Ankle         0
Biceps        1
Forearm       0
Wrist         0
BodyCat       0
dtype: int64